name: Scribe Docker Release

on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        description: The version to generate

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_preset: ["py311"]
        platform: ["linux/amd64", "linux/arm64"]
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        shell: bash
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          pip install click
          ./scripts/build_docker.py \
            ${{ matrix.build_preset }} \
            "release" \
            --build_context_ref "$RELEASE" \
            --platform ${{ matrix.platform }}
