name: Scribe Docker Release

on:
  workflow_dispatch:
    inputs:
      release_index:
        required: true
        
permissions:
  id-token: write
  contents: read

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_preset: ["py311"]
        platform: ["linux/amd64", "linux/arm64"]
      fail-fast: false

    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        shell: bash
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          pip install click
          ./scripts/build_docker.py \
            ${{ matrix.build_preset }} \
            "release" \
            --build_context_ref "${{ github.ref_name }}-${{ inputs.release_index }}" \
            --platform ${{ matrix.platform }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SCRIBE2_GITHUB_ROLE }}
          role-session-name: Github
          aws-region: il-central-1

      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region il-central-1 | docker login --username AWS --password-stdin 975050347682.dkr.ecr.il-central-1.amazonaws.com

      - name: Tag Docker Image
        run: |
          IMAGE_TAG="${{ github.ref_name }}-${{ inputs.release_index }}-py311"
          REPOSITORY="975050347682.dkr.ecr.il-central-1.amazonaws.com/superset-base-image"
          docker tag $IMAGE_TAG $REPOSITORY:$IMAGE_TAG

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG="${{ github.ref_name }}-${{ inputs.release_index }}-py311"
          REPOSITORY="975050347682.dkr.ecr.il-central-1.amazonaws.com/superset-base-image"
          docker push $REPOSITORY:$IMAGE_TAG
          
      - name: Print Docker Image Tag
        run: |
          IMAGE_TAG="${{ github.ref_name }}-${{ inputs.release_index }}-py311"
          echo $IMAGE_TAG
          docker push $REPOSITORY:$IMAGE_TAG
